from building import *

group = []

if not GetDepend(['RT_USING_MTD_NOR']) and not GetDepend(['RT_USING_MTD_NAND']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = []

if GetDepend(['RT_USING_MTD_NOR']):
    src += ['mtd_nor.c']

if GetDepend(['RT_USING_MTD_NAND']):
    src += ['mtd_nand.c']

if GetDepend(['RT_USING_MTD_NOR_CFI']):
    src += ['mtd-cfi.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
