# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')

CPPPATH = [cwd]

if not GetDepend(['RT_FIRMWARE_QEMU_FW_CFG', 'RT_VIDEO_FB']):
    SrcRemove(src, ['drv_romfb.c'])

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
