from building import *
import re

group   = []

if not GetDepend(['RT_VIDEO_LOGO']):
    Return('group')

cwd     = GetCurrentDir()
CPPPATH = [cwd + '/../../include']
CPPDEFINES = []

src     = []

logo_path = None
logo_width = 0
logo_height = 0
logo_gray = 0

if GetDepend(['RT_VIDEO_LOGO_RT_THREAD_CLUT224']):
    logo_path = cwd + '/logo-rt-thread-clut224.ppm'

if GetDepend(['RT_VIDEO_LOGO_RT_THREAD_WHITE_CLUT224']):
    logo_path = cwd + '/logo-rt-thread-white-clut224.ppm'

if GetDepend(['RT_VIDEO_LOGO_BSP']):
    logo_path = Dir('#').abspath + '/' + GetConfigValue('RT_VIDEO_LOGO_BSP_PATH').strip('"')

if logo_path != None:
    with open(logo_path, 'rb') as ppm:
        data = ppm.read().split(b'\n')

        # PPM: <magic number>
        magic = data[0].decode('utf-8')

        # PPM: <comment>
        offset = 1
        while True:
            comment = str(data[offset].decode('utf-8'))
            if comment[0] != '#':
                break
            offset += 1

        # PPM: <width> <height>
        logo_width, logo_height = map(int, data[offset].split())

        # PPM: <max pixel value>
        max_val = int(data[offset + 1])

        # PPM: <data>
        ppm.seek(0)
        pixels = b''.join(ppm.readlines()[offset + 2:])
        ppm.close()

        if magic == 'P1' or magic == 'P2' or magic == 'P3':
            # ASCII
            pixels = re.sub(b'\\s+', b'\n', pixels.strip()).decode('utf-8').split('\n')

    logo = open(cwd + '/logo.inc', "w")

    if max_val != 255:
        logo_gray = 1
        for dy in range(logo_height):
            for dx in range(logo_width):
                pixel = pixels[dy * logo_width + dx]
                logo.write(str(pixel) + ",")
            logo.write("\n")
    else:
        for dy in range(logo_height):
            for dx in range(logo_width):
                index = (dy * logo_width + dx) * 3
                # Red
                logo.write(str(pixels[index]).rjust(4) + ",")
                # Green
                logo.write(str(pixels[index + 1]).rjust(4) + ",")
                # Blue
                logo.write(str(pixels[index + 2]).rjust(4) + ",")
            logo.write("\n")

    logo.close()

    CPPDEFINES += ['__RT_THREAD_STARTUP_LOGO_WIDTH__="' + str(logo_width) + '"']
    CPPDEFINES += ['__RT_THREAD_STARTUP_LOGO_HEIGHT__="' + str(logo_height) + '"']
    CPPDEFINES += ['__RT_THREAD_STARTUP_LOGO_GRAY__="' + str(logo_gray) + '"']
    src += ['logo.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)
Return('group')
