from building import *

group = []

if not GetDepend(['RT_USING_I2C']) and not GetDepend(['RT_USING_DM']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../../include']

src = []

if GetDepend('RT_I2C_RK3X'):
    src += ['i2c-rk3x.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
