from building import *

group   = []

if not GetDepend(['RT_SOC_ROCKCHIP']):
    Return('group')

cwd     = GetCurrentDir()
CPPPATH = [cwd + '/../../include']

src     = []

if GetDepend(['RT_SOC_ROCKCHIP_FIQ_DEBUGGER']):
    src += ['rk_fiq_debugger.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)
Return('group')