Import('RTT_ROOT')
from building import *

objs = []

cwd = GetCurrentDir()
src = Split("""
i2c_core.c
i2c_dev.c
""")

if GetDepend('RT_USING_I2C_BITOPS'):
    src = src + ['i2c-bit-ops.c']

# The set of source files associated with this SConscript file.
path = [cwd + '/../include']

if GetDepend(['RT_USING_DM']):
    src += ['i2c_bus.c', 'i2c_dm.c']

group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_I2C'], CPPPATH = path)

for d in os.listdir(cwd):
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group

Return('objs')